apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openpaynet-app-secrets
  namespace: openpaynet
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: openpaynet-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: openpaynet/prod/jwt
    - secretKey: TOKEN_ISSUER_ADMIN_KEY
      remoteRef:
        key: openpaynet/prod/token-issuer-admin-key
    - secretKey: TOKENIZATION_SECRET
      remoteRef:
        key: openpaynet/prod/tokenization
    - secretKey: MERCHANT_CREDENTIALS_JSON
      remoteRef:
        key: openpaynet/prod/merchant-credentials
    - secretKey: SUBJECT_POLICIES_JSON
      remoteRef:
        key: openpaynet/prod/subject-policies
    - secretKey: POSTGRES_DB
      remoteRef:
        key: openpaynet/prod/postgres-db
    - secretKey: POSTGRES_USER
      remoteRef:
        key: openpaynet/prod/postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: openpaynet/prod/postgres-password
    - secretKey: ELASTICSEARCH_PASSWORD
      remoteRef:
        key: openpaynet/prod/elasticsearch-password
