apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openpaynet-gateway
  namespace: openpaynet
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
    - hosts:
        - openpaynet.local
      secretName: openpaynet-tls
  rules:
    - host: openpaynet.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000
